spring:
  datasource:
    url: jdbc:mysql://db:3306/azan_kz
    username: ${db-username}
    password: ${db-password}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  output:
    ansi.enabled: always
