spring:
  datasource:
    url: jdbc:mysql://db:3306/azan_kz?characterEncoding=UTF-8
    username: ${db-username}
    password: ${db-password}
  jpa:
    database: mysql
  output:
    ansi.enabled: always
